### PR TITLE
TCP server and other goodies

### PR DESCRIPTION
**Pull request by yodalf**
This is an add-on to simple-cli.py but also could be a separate program.
I think it is better as an add-on, though.

### CODE REVIEW

**Comment by touretzkyds** [comment]
This change breaks command line editing. For example, in the original version I can use control-P and control-N to move through the history list. The modified code you submitted disables this feature.  Can you figure out how to restore it?

**Comment by yodalf** [comment]
This is caused by the fact that I removed the '-i' in the invocation line. I did that in order to have a clean exit (no dangling python shell) upon the 'exit' command.

In order to keep the clean exit, I added code that could normally be in the .pythonstartup file, since it is so useful.  However, that code writes history data in a file...

If this is not OK with you, then just remove that extra code and keep the '-i' on the first line... No problem!

**Comment by touretzkyds** [comment]
There's another problem with this modification: control-C exits Python. So if I type some expression that doesn't return and I want to control-C out of it and continue, I can't do that. Do I have to put the -i flag back in to fix this?

**Comment by yodalf** [comment]
Removing the "-i" has many side effects.  You might want to simply bring it back, considering your initial requirements for the simple-cli ...

My wish for a "clean exit" removes too much of the functionality you need, feel free to revert things back!

Real

**Comment by yodalf** [comment]
Hello,

This is why I used your CLI for:

https://forums.anki.com/t/how-to-run-node-red-alongside-the-cozmo-app/2109?u=realo

Node-Red is quite fun to use with Cozmo.  Very easy to get cool results, fast.

Now, I just discovered "ROS" last week, and will look into that. ROS seems quite powerful, but not as fun as Node-Red.  A serious tool, for serious business...  

Real

**Pull request merged**
