### PR TITLE
Cleaned up code for merge with master

### PR DESCRIPTION
**Pull request by Shade5**
Fixed variable names.
Includes stable sharedmap and doorpass code.
Bugs may be present, seems stable with initial tests.

### CODE REVIEW

**Comment by touretzkyds** [comment]
There are a couple of issues with sharedmap.py. A syntax error on line 201, and a missing newline at the end of the file. I've fixed these in the devel branch of my cozmo-tools repository. I've done some testing with the perched camera and things seem to work.

One issue: I see the camera object in the particle viewer, but I'm not seeing it in the worldmap viewer.

**Comment by touretzkyds** [comment]
I showed the robot a marker (marker 45) and it added a marker object to the world map. But the key was 'Wall-43', which surprised me. I would expect that key to have a value that was a WallObj, not a MarkerObj. Shouldn't we use 'Marker-43' as the key until we have enough markers to make a wall?

**Comment by Shade5** [comment]
I was using the same key name for the WallObj and the MarkerObj as they actually represent the same object. The MarkerObj is not placed at the location of the marker but at the estimated center of the wall ( Maybe a better name would be EstimatedWallObj ). They can still be differentiated using based on the value types. But I have changed the names of the keys to avoid confusion.

**Comment by Shade5** [comment]
I have made all the changes you suggested and fixed a few more cases. Please have a look.

**Pull request merged**
